theme: jekyll-theme-minimal
title: My Dev AI Blog
description: Sharing my journey through AI and development
# Load custom CSS on top of theme
defaults:
  -
    scope:
      path: ""
    values:
      css: /assets/css/style.css
header: image: /assets/images/banner.jpg
