theme: jekyll-theme-cayman
baseurl: "/my-dev_ai-blog"
url: "https://phans09.github.io
# Optional - tweak colors
color_scheme: light
title: My Dev AI Blog
description: Sharing my journey through AI, coding, development and learning. 
# Load custom CSS on top of theme
defaults:
  -
    scope:
      path: ""
    values:
      css: /assets/css/style.css
header: image: /assets/images/banner.jpg
